version: "3.8"

networks:
  servers:

services:

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    networks:
      - servers
    ports:
      - "8083:8083"
    volumes:
      - dbdata:/app/data

  server1:
    build: .
    networks:
      - servers
    ports:
      - "8080:8080"
    environment:
      - CONF_RESPONSE_DELAY_SEC=0
    depends_on:
      - db

  server2:
    build: .
    networks:
      - servers
    ports:
      - "8081:8080"
    environment:
      - CONF_RESPONSE_DELAY_SEC=0
    depends_on:
      - db

  server3:
    build: .
    networks:
      - servers
    ports:
      - "8082:8080"
    environment:
      - CONF_RESPONSE_DELAY_SEC=0
    depends_on:
      - db

  balancer:
    build: .
    command: ["lb", "--trace=true", "--timeout-sec=5"]
    networks:
      - servers
    ports:
      - "8090:8090"
    depends_on:
      - server1
      - server2
      - server3

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - servers
    depends_on:
      - balancer
      - server1
      - server2
      - server3
    environment:
      - GO111MODULE=on
    command: ["go", "test", "-v", "./integration", "-timeout=60s"]

volumes:
  dbdata:
